// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxmpbmveegkpalmgdnur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bXBibXZlZWdrcGFsbWdkbnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODc0NzIsImV4cCI6MjA2NTQ2MzQ3Mn0.keQ510eQADIUIDeqz1XUhmf0wYfApi1o0w11Lc4T2j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);